---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Restart systemd-zram-setup
  ansible.builtin.systemd_service:
    name: "{{ zram_service_name }}"
    state: restarted
