---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes

- name: Restart systemd-zram-setup
  ansible.builtin.systemd_service:
    name: systemd-zram-setup@zram0.service
    state: restarted
