---
- name: Include base prereq tasks
  ansible.builtin.include_tasks: prereqs.yml

- name: Include base upgrade tasks
  ansible.builtin.include_tasks: upgrade.yml

- name: Include base config tasks
  ansible.builtin.include_tasks: config.yml
