---
- name: Manage unattended-upgrades
  when: automatic_updates_enabled | bool
  block:
    - name: Install unattended-upgrades
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Configure apt periodic updates
      ansible.builtin.template:
        src: 20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: "0644"

    - name: Configure unattended-upgrades security origins
      ansible.builtin.template:
        src: 51unattended-upgrades-security-only.j2
        dest: /etc/apt/apt.conf.d/51unattended-upgrades-security-only
        owner: root
        group: root
        mode: "0644"

    - name: Configure unattended-upgrades local settings
      ansible.builtin.template:
        src: 52unattended-upgrades-local.j2
        dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
        owner: root
        group: root
        mode: "0644"

    - name: Enable apt update timers
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer

- name: Remove unattended-upgrades
  when: not automatic_updates_enabled | bool
  block:
    - name: Disable apt update timers
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer

    - name: Remove apt periodic update configuration
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/apt.conf.d/20auto-upgrades
        - /etc/apt/apt.conf.d/51unattended-upgrades-security-only
        - /etc/apt/apt.conf.d/52unattended-upgrades-local

    - name: Purge unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: absent
        purge: true
